export const MAX_HERO_HEALTH = 30;
export const MAX_MANA = 10;
export const MAX_BOARD_SIZE = 7;
export const MAX_HAND_SIZE = 6;
export const FIRST_PLAYER_HAND_SIZE = 3;
export const SECOND_PLAYER_HAND_SIZE = 4;
export const DECK_SIZE = 30;
export const ROOM_IDLE_TTL_MS = 10 * 60 * 1000;
export const ROOM_SWEEP_INTERVAL_MS = 60 * 1000;
