export enum ClientEvents {
  CREATE_ROOM = 'CREATE_ROOM',
  JOIN_ROOM = 'JOIN_ROOM',
  SUBMIT_LOADOUT = 'SUBMIT_LOADOUT',
  PLAY_CARD = 'PLAY_CARD',
  ATTACK = 'ATTACK',
  END_TURN = 'END_TURN',
  USE_HERO_POWER = 'USE_HERO_POWER',
  CONCEDE = 'CONCEDE',
  RECONNECT_GAME = 'RECONNECT_GAME',
  REMATCH = 'REMATCH',
}

export enum ServerEvents {
  ROOM_CREATED = 'ROOM_CREATED',
  PLAYER_JOINED = 'PLAYER_JOINED',
  ROOM_READY = 'ROOM_READY',
  LOADOUT_ACCEPTED = 'LOADOUT_ACCEPTED',
  GAME_STARTED = 'GAME_STARTED',
  GAME_STATE_UPDATED = 'GAME_STATE_UPDATED',
  ACTION_REJECTED = 'ACTION_REJECTED',
  GAME_OVER = 'GAME_OVER',
  PLAYER_DISCONNECTED = 'PLAYER_DISCONNECTED',
}
