export enum ClientEvents {
  CREATE_ROOM = 'CREATE_ROOM',
  JOIN_ROOM = 'JOIN_ROOM',
  SELECT_DECK = 'SELECT_DECK',
  START_GAME = 'START_GAME',
  PLAY_CARD = 'PLAY_CARD',
  ATTACK = 'ATTACK',
  END_TURN = 'END_TURN',
  USE_HERO_POWER = 'USE_HERO_POWER',
  DRAW_CARD = 'DRAW_CARD',
  CONCEDE = 'CONCEDE',
  RECONNECT_GAME = 'RECONNECT_GAME',
  REMATCH = 'REMATCH',
}

export enum ServerEvents {
  ROOM_CREATED = 'ROOM_CREATED',
  PLAYER_JOINED = 'PLAYER_JOINED',
  ROOM_READY = 'ROOM_READY',
  DECK_SELECTED = 'DECK_SELECTED',
  GAME_STARTED = 'GAME_STARTED',
  GAME_STATE_UPDATED = 'GAME_STATE_UPDATED',
  ACTION_REJECTED = 'ACTION_REJECTED',
  TURN_CHANGED = 'TURN_CHANGED',
  GAME_OVER = 'GAME_OVER',
  PLAYER_DISCONNECTED = 'PLAYER_DISCONNECTED',
  REMATCH_REQUESTED = 'REMATCH_REQUESTED',
}

export const TURN_CHANGE_MESSAGES = {
  FIRST_PLAYER_START: 'HERO 1 STARTS',
  SECOND_PLAYER_START: 'HERO 2 STARTS',
  END_TURN_IN: 'END TURN IN',
} as const;
